# Generated by Django 6.0.5 on 2026-05-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
