# Generated by Django 6.0.5 on 2026-05-10 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_entries', to='surveys.survey')),
            ],
            options={
                'ordering': ('email',),
                'constraints': [models.UniqueConstraint(fields=('survey', 'email'), name='unique_survey_access_email')],
            },
        ),
    ]
