# Generated by Django 6.0.5 on 2026-05-10 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_surveyresponse_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='close_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='open_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('respondent__isnull', False)), fields=('survey', 'respondent'), name='unique_survey_response_user'),
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('respondent_email', ''), _negated=True), fields=('survey', 'respondent_email'), name='unique_survey_response_email'),
        ),
    ]
