# Generated by Codex on 2026-05-11

import uuid

from django.db import migrations, models


def populate_survey_uuids(apps, schema_editor):
    Survey = apps.get_model('surveys', 'Survey')
    for survey in Survey.objects.filter(uuid__isnull=True):
        survey.uuid = uuid.uuid4()
        survey.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_survey_close_at_survey_open_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='uuid',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(populate_survey_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='survey',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]
